site_name: SDF
site_url: https://pdmosses.github.io/sdf/
repo_name: pdmosses/sdf
repo_url: https://github.com/pdmosses/sdf/

theme:
  name: material

  features:
    - content.code.copy
    # - navigation.expand
    - navigation.indexes 
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: false
      strict: false
      order: asc
      sort_type: natural
      order_by: title

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/MetaBorg.css
  - stylesheets/TemplateLang-sorts.css
  - stylesheets/TemplateLang.css
